<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10860" started-at="2015-02-17T07:30:05Z" finished-at="2015-02-17T07:30:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10860" started-at="2015-02-17T07:30:05Z" finished-at="2015-02-17T07:30:15Z">
      <class name="com.example.tests.ContactCreationTests">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.example.tests.ContactCreationTests@140d5f0]" name="setUp" is-config="true" duration-ms="46" started-at="2015-02-17T13:30:05Z" finished-at="2015-02-17T13:30:05Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testUiAndDbConformsWithModel()[pri:0, instance:com.example.tests.ContactCreationTests@140d5f0]" name="testUiAndDbConformsWithModel" duration-ms="7690" started-at="2015-02-17T13:30:05Z" finished-at="2015-02-17T13:30:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: <Contacts [storedConacts=[Contact [43: Name1029314288, Email1968849739], Contact [44: Name1029314288, Email1968849739], Contact [45: Name1029314288, Email1968849739]]]]]><![CDATA[>
     but: was <Contacts [storedConacts=[Contact [43: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795], Contact [44: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795], Contact [45: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795]]]><![CDATA[]]]]><![CDATA[>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: <Contacts [storedConacts=[Contact [43: Name1029314288, Email1968849739], Contact [44: Name1029314288, Email1968849739], Contact [45: Name1029314288, Email1968849739]]]]]><![CDATA[>
     but: was <Contacts [storedConacts=[Contact [43: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795], Contact [44: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795], Contact [45: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795]]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.example.tests.ContactCreationTests.testUiAndDbConformsWithModel(ContactCreationTests.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUiAndDbConformsWithModel -->
        <test-method status="PASS" signature="testValidContactCanBeCreated(com.example.fw.ContactObject)[pri:0, instance:com.example.tests.ContactCreationTests@140d5f0]" name="testValidContactCanBeCreated" duration-ms="2806" started-at="2015-02-17T13:30:12Z" data-provider="contactsFromFile" finished-at="2015-02-17T13:30:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Contact [46: Name1029314288, Email1968849739]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidContactCanBeCreated -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.ContactCreationTests@140d5f0]" name="tearDown" is-config="true" duration-ms="301" started-at="2015-02-17T13:30:15Z" finished-at="2015-02-17T13:30:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.ContactCreationTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
